# Generated by Django 5.2 on 2025-05-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=20)),
                ('lokasi', models.CharField(max_length=40)),
            ],
        ),
    ]
