# Generated by Django 5.2.1 on 2025-05-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(choices=[('Anggota Security', 'Anggota Security'), ('Danru Security', 'Danru Security'), ('Chief Security', 'Chief Security'), ('Staff Operasional', 'Staff Operasional'), ('Direktur', 'Direktur'), ('Direktur Keuangan', 'Direktur Keuangan'), ('Manager Operasional', 'Manager Operasional'), ('Koordinator Lapangan', 'Koordinator Lapangan')], max_length=20)),
                ('lokasi', models.CharField(max_length=40)),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('pendidikan', models.CharField(choices=[('SMA', 'SMA'), ('S1', 'S1'), ('S2', 'S2')], max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15)),
                ('status', models.CharField(choices=[('TK/0', 'TK/0'), ('TK/1', 'TK/1'), ('TK/2', 'TK/2'), ('K/0', 'K/0'), ('K/1', 'K/1'), ('K/2', 'K/2')], max_length=5)),
                ('nomor_kk', models.CharField(max_length=16)),
                ('alamat_ktp', models.CharField(max_length=100)),
                ('alamat_tinggal', models.CharField(max_length=100)),
                ('ibu', models.CharField(max_length=40)),
                ('nohp', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
