# Generated by Django 5.2.1 on 2025-05-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Nomer Karyawan')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama')),
                ('jabatan', models.CharField(choices=[('Anggota Security', 'Anggota Security'), ('Danru Security', 'Danru Security'), ('Chief Security', 'Chief Security'), ('Staff Operasional', 'Staff Operasional'), ('Direktur', 'Direktur'), ('Direktur Keuangan', 'Direktur Keuangan'), ('Manager Operasional', 'Manager Operasional'), ('Koordinator Lapangan', 'Koordinator Lapangan')], max_length=20, verbose_name='Jabatan')),
                ('lokasi', models.CharField(max_length=40, verbose_name='Lokasi Pekerjaan')),
                ('nik', models.CharField(max_length=16, unique=True, verbose_name='NIK')),
                ('pendidikan', models.CharField(choices=[('SMA', 'SMA'), ('S1', 'S1'), ('S2', 'S2')], max_length=100, verbose_name='Pendidikan Terakhir')),
                ('tempat_lahir', models.CharField(max_length=100, verbose_name='Tempat Lahir')),
                ('kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15, verbose_name='Jenis Kelamin')),
                ('status', models.CharField(choices=[('TK/0', 'TK/0'), ('TK/1', 'TK/1'), ('TK/2', 'TK/2'), ('K/0', 'K/0'), ('K/1', 'K/1'), ('K/2', 'K/2')], max_length=5, verbose_name='Status')),
                ('nomor_kk', models.CharField(max_length=16, verbose_name='Nomer KK')),
                ('alamat_ktp', models.CharField(max_length=100, verbose_name='Alamat KTP')),
                ('alamat_tinggal', models.CharField(max_length=100, verbose_name='Alamat Domisili')),
                ('ibu_kandung', models.CharField(max_length=40, verbose_name='Nama Ibu Kandung')),
                ('nohp', models.CharField(max_length=13, verbose_name='Nomer Handphone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
        ),
    ]
