# Generated by Django 5.2.1 on 2025-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(choices=[('Anggota Security', 'Anggota Security'), ('Danru Security', 'Danru Security'), ('Chief Security', 'Chief Security'), ('Staff Operasional', 'Staff Operasional'), ('Direktur', 'Direktur'), ('Direktur Keuangan', 'Direktur Keuangan'), ('Manager Operasional', 'Manager Operasional'), ('HRD', 'HRD')], max_length=20),
        ),
    ]
