# Generated by Django 5.2.1 on 2025-05-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_alter_karyawan_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_lahir',
            field=models.DateField(default='1996-10-09'),
            preserve_default=False,
        ),
    ]
