# Generated by Django 5.2.1 on 2025-05-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0003_karyawan_tanggal_lahir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='karyawan',
            old_name='nohp',
            new_name='no_hp',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='tanggal_lahir',
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='nik',
            field=models.CharField(max_length=16),
        ),
    ]
